### ISSUE TITLE
Problems setting normalizeVolume attribute on Feed.Player

### ISSUE THREAD

**Issue by drakipovic** [feedfm/Javascript-SDK#7]
Hi,

it seems that this [line](https://github.com/feedfm/Javascript-SDK/blob/4b02c22ccd1574d36315d87f761594c28a370be8/src/player.js#L91) is not correct, I'm trying to send it normalizeVolume: false through options parameter `new Feed.Player(token, secret, { normalizeVolume: false })`, but because of || true condition it is always set to true.

**Comment by eml** [comment]
ouch! you are right! I just built and published 1.99.22 with a fix for this and published it.
